import { Poppins } from "next/font/google"; 
import "./globals.css";
import Footer from "./Components/Layouts/Footer";
import Navbar from "./Components/Navbar";

const poppins = Poppins(
  {
    weight:["100", "200", "400", "500", "600", "800"],
  }
)

export const metadata = {
  title: {
    default: "Care.xyz",
  template: "%s | Care.xyz",
  }, 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#f1f2f6]`}
      >
        <header>
          <Navbar></Navbar>
        </header>

        {children}

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
